# create products table

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision = '50393f78c2da'
down_revision = 'acbe31279739'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('products', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'products', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'products', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'updated_by')
    op.drop_column('products', 'created_by')
    # ### end Alembic commands ###
